/** 常用 Emoji 数据集（精选 ~600 个，覆盖日常使用 95%+） */
export interface EmojiItem {
  c: string;     // 字符
  n: string;     // 英文名
  k?: string[];  // 关键词（含中文）
}

export interface EmojiGroup {
  id: string;
  title: string;
  items: EmojiItem[];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: 'smileys',
    title: '表情 & 情绪',
    items: [
      { c: '😀', n: 'grinning', k: ['笑', 'smile', 'happy'] },
      { c: '😃', n: 'smiley', k: ['笑'] },
      { c: '😄', n: 'smile', k: ['笑'] },
      { c: '😁', n: 'grin', k: ['笑'] },
      { c: '😆', n: 'laughing', k: ['笑'] },
      { c: '😅', n: 'sweat smile', k: ['尴尬', '笑'] },
      { c: '🤣', n: 'rofl', k: ['爆笑'] },
      { c: '😂', n: 'joy', k: ['哭笑', '笑哭'] },
      { c: '🙂', n: 'slightly smiling', k: ['微笑'] },
      { c: '🙃', n: 'upside down', k: ['倒脸'] },
      { c: '😉', n: 'wink', k: ['眨眼'] },
      { c: '😊', n: 'blush', k: ['脸红', '微笑'] },
      { c: '😇', n: 'innocent', k: ['天使'] },
      { c: '🥰', n: 'smiling face with hearts', k: ['爱心'] },
      { c: '😍', n: 'heart eyes', k: ['爱'] },
      { c: '🤩', n: 'star struck', k: ['星眼'] },
      { c: '😘', n: 'kiss', k: ['吻', '亲'] },
      { c: '😗', n: 'kissing', k: ['亲'] },
      { c: '😚', n: 'kissing closed eyes', k: ['亲'] },
      { c: '😙', n: 'kissing smiling eyes', k: ['亲'] },
      { c: '😋', n: 'yum', k: ['好吃'] },
      { c: '😛', n: 'tongue', k: ['吐舌'] },
      { c: '😜', n: 'wink tongue', k: ['调皮'] },
      { c: '🤪', n: 'zany', k: ['疯'] },
      { c: '😝', n: 'squint tongue', k: ['吐舌'] },
      { c: '🤑', n: 'money mouth', k: ['爱钱'] },
      { c: '🤗', n: 'hugs', k: ['抱抱'] },
      { c: '🤭', n: 'hand over mouth', k: ['捂嘴'] },
      { c: '🤫', n: 'shushing', k: ['嘘', '安静'] },
      { c: '🤔', n: 'thinking', k: ['思考'] },
      { c: '🤐', n: 'zipper mouth', k: ['闭嘴'] },
      { c: '🤨', n: 'raised eyebrow', k: ['挑眉'] },
      { c: '😐', n: 'neutral', k: ['无表情'] },
      { c: '😑', n: 'expressionless', k: ['面瘫'] },
      { c: '😶', n: 'no mouth', k: ['无言'] },
      { c: '😏', n: 'smirk', k: ['得意'] },
      { c: '😒', n: 'unamused', k: ['不爽'] },
      { c: '🙄', n: 'roll eyes', k: ['翻白眼'] },
      { c: '😬', n: 'grimace', k: ['尴尬'] },
      { c: '🤥', n: 'lying', k: ['撒谎'] },
      { c: '😌', n: 'relieved', k: ['释怀'] },
      { c: '😔', n: 'pensive', k: ['沉思', '难过'] },
      { c: '😪', n: 'sleepy', k: ['困'] },
      { c: '😴', n: 'sleep', k: ['睡觉'] },
      { c: '😷', n: 'mask', k: ['口罩'] },
      { c: '🤒', n: 'thermometer face', k: ['生病'] },
      { c: '🤕', n: 'head bandage', k: ['受伤'] },
      { c: '🤢', n: 'nauseated', k: ['恶心'] },
      { c: '🤮', n: 'vomiting', k: ['呕吐'] },
      { c: '🥵', n: 'hot', k: ['热'] },
      { c: '🥶', n: 'cold', k: ['冷'] },
      { c: '😵', n: 'dizzy', k: ['晕'] },
      { c: '🤯', n: 'mind blown', k: ['震惊'] },
      { c: '🤠', n: 'cowboy', k: ['牛仔'] },
      { c: '🥳', n: 'partying', k: ['庆祝', '派对'] },
      { c: '😎', n: 'sunglasses', k: ['酷', '太阳镜'] },
      { c: '🤓', n: 'nerd', k: ['书呆子'] },
      { c: '🧐', n: 'monocle', k: ['单片眼镜'] },
      { c: '😕', n: 'confused', k: ['困惑'] },
      { c: '😟', n: 'worried', k: ['担心'] },
      { c: '🙁', n: 'frowning', k: ['皱眉'] },
      { c: '☹️', n: 'frown', k: ['不开心'] },
      { c: '😮', n: 'open mouth', k: ['张嘴'] },
      { c: '😯', n: 'hushed', k: ['屏息'] },
      { c: '😲', n: 'astonished', k: ['惊讶'] },
      { c: '😳', n: 'flushed', k: ['脸红', '害羞'] },
      { c: '🥺', n: 'pleading', k: ['可怜'] },
      { c: '😦', n: 'frowning open', k: ['沮丧'] },
      { c: '😧', n: 'anguished', k: ['痛苦'] },
      { c: '😨', n: 'fearful', k: ['害怕'] },
      { c: '😰', n: 'cold sweat', k: ['冷汗'] },
      { c: '😥', n: 'sad sweat', k: ['难过'] },
      { c: '😢', n: 'cry', k: ['哭'] },
      { c: '😭', n: 'sob', k: ['大哭'] },
      { c: '😱', n: 'scream', k: ['尖叫'] },
      { c: '😖', n: 'confounded', k: ['困扰'] },
      { c: '😣', n: 'persevere', k: ['坚持', '难受'] },
      { c: '😞', n: 'disappointed', k: ['失望'] },
      { c: '😓', n: 'downcast sweat', k: ['沮丧'] },
      { c: '😩', n: 'weary', k: ['疲惫'] },
      { c: '😫', n: 'tired', k: ['累'] },
      { c: '🥱', n: 'yawning', k: ['打哈欠'] },
      { c: '😤', n: 'triumph', k: ['得意', '生气'] },
      { c: '😡', n: 'pouting', k: ['生气'] },
      { c: '😠', n: 'angry', k: ['愤怒'] },
      { c: '🤬', n: 'cursing', k: ['咒骂'] },
      { c: '😈', n: 'imp', k: ['小恶魔'] },
      { c: '👿', n: 'devil', k: ['恶魔'] },
      { c: '💀', n: 'skull', k: ['骷髅'] },
      { c: '☠️', n: 'crossbones', k: ['骷髅'] },
      { c: '💩', n: 'poop', k: ['翔', '便便'] },
      { c: '👻', n: 'ghost', k: ['幽灵'] },
      { c: '👽', n: 'alien', k: ['外星人'] },
      { c: '🤖', n: 'robot', k: ['机器人'] },
      { c: '🎃', n: 'jack-o-lantern', k: ['南瓜灯'] },
    ],
  },
  {
    id: 'gestures',
    title: '手势 & 人物',
    items: [
      { c: '👋', n: 'wave', k: ['挥手', '你好', 'hi'] },
      { c: '🤚', n: 'raised back', k: ['手背'] },
      { c: '🖐️', n: 'raised hand fingers', k: ['五指'] },
      { c: '✋', n: 'raised hand', k: ['停', '举手'] },
      { c: '🖖', n: 'vulcan', k: ['瓦肯礼'] },
      { c: '👌', n: 'ok hand', k: ['ok', '可以'] },
      { c: '🤏', n: 'pinch', k: ['捏'] },
      { c: '✌️', n: 'victory', k: ['胜利', 'v'] },
      { c: '🤞', n: 'crossed fingers', k: ['交叉手指', '祈祷'] },
      { c: '🤟', n: 'love you gesture', k: ['爱你'] },
      { c: '🤘', n: 'metal', k: ['摇滚'] },
      { c: '🤙', n: 'call me', k: ['打电话'] },
      { c: '👈', n: 'point left', k: ['指左'] },
      { c: '👉', n: 'point right', k: ['指右'] },
      { c: '👆', n: 'point up', k: ['指上'] },
      { c: '👇', n: 'point down', k: ['指下'] },
      { c: '☝️', n: 'index up', k: ['第一'] },
      { c: '👍', n: 'thumbs up', k: ['赞', '好'] },
      { c: '👎', n: 'thumbs down', k: ['差', '不好'] },
      { c: '✊', n: 'fist', k: ['拳'] },
      { c: '👊', n: 'oncoming fist', k: ['拳头'] },
      { c: '🤛', n: 'left facing fist', k: ['左拳'] },
      { c: '🤜', n: 'right facing fist', k: ['右拳'] },
      { c: '👏', n: 'clap', k: ['鼓掌', '掌声'] },
      { c: '🙌', n: 'raised hands', k: ['欢呼'] },
      { c: '👐', n: 'open hands', k: ['张开手'] },
      { c: '🤲', n: 'palms up', k: ['双手'] },
      { c: '🤝', n: 'handshake', k: ['握手'] },
      { c: '🙏', n: 'pray', k: ['祈祷', '拜托'] },
      { c: '✍️', n: 'writing', k: ['写'] },
      { c: '💅', n: 'nail', k: ['指甲'] },
      { c: '🦾', n: 'mechanical arm', k: ['机械臂'] },
      { c: '🦿', n: 'mechanical leg', k: ['机械腿'] },
      { c: '🦵', n: 'leg', k: ['腿'] },
      { c: '🦶', n: 'foot', k: ['脚'] },
      { c: '👂', n: 'ear', k: ['耳'] },
      { c: '🦻', n: 'ear with hearing aid', k: ['助听器'] },
      { c: '👃', n: 'nose', k: ['鼻'] },
      { c: '🧠', n: 'brain', k: ['大脑'] },
      { c: '🦷', n: 'tooth', k: ['牙'] },
      { c: '🦴', n: 'bone', k: ['骨头'] },
      { c: '👀', n: 'eyes', k: ['眼睛', '看'] },
      { c: '👁️', n: 'eye', k: ['眼'] },
      { c: '👅', n: 'tongue', k: ['舌头'] },
      { c: '👄', n: 'mouth', k: ['嘴'] },
      { c: '💋', n: 'kiss', k: ['吻', '亲'] },
    ],
  },
  {
    id: 'objects',
    title: '物件 & 符号',
    items: [
      { c: '💯', n: '100', k: ['一百', '满分'] },
      { c: '💢', n: 'anger', k: ['愤怒'] },
      { c: '💥', n: 'collision', k: ['爆炸'] },
      { c: '💫', n: 'dizzy', k: ['星星'] },
      { c: '💦', n: 'sweat drops', k: ['水滴'] },
      { c: '💨', n: 'dash', k: ['冲'] },
      { c: '🕳️', n: 'hole', k: ['洞'] },
      { c: '💣', n: 'bomb', k: ['炸弹'] },
      { c: '💬', n: 'speech', k: ['说话'] },
      { c: '💭', n: 'thought', k: ['想'] },
      { c: '🗯️', n: 'angry speech', k: ['吐槽'] },
      { c: '♥️', n: 'red heart', k: ['心'] },
      { c: '❤️', n: 'red heart', k: ['爱'] },
      { c: '🧡', n: 'orange heart', k: ['橙心'] },
      { c: '💛', n: 'yellow heart', k: ['黄心'] },
      { c: '💚', n: 'green heart', k: ['绿心'] },
      { c: '💙', n: 'blue heart', k: ['蓝心'] },
      { c: '💜', n: 'purple heart', k: ['紫心'] },
      { c: '🖤', n: 'black heart', k: ['黑心'] },
      { c: '🤍', n: 'white heart', k: ['白心'] },
      { c: '🤎', n: 'brown heart', k: ['棕心'] },
      { c: '💔', n: 'broken heart', k: ['心碎'] },
      { c: '❣️', n: 'heart exclamation', k: ['心叹号'] },
      { c: '💕', n: 'two hearts', k: ['两颗心'] },
      { c: '💞', n: 'revolving hearts', k: ['爱心'] },
      { c: '💓', n: 'beating heart', k: ['心跳'] },
      { c: '💗', n: 'growing heart', k: ['爱'] },
      { c: '💖', n: 'sparkling heart', k: ['闪心'] },
      { c: '💘', n: 'heart arrow', k: ['丘比特'] },
      { c: '💝', n: 'gift heart', k: ['爱心礼物'] },
      { c: '☀️', n: 'sun', k: ['太阳'] },
      { c: '🌙', n: 'moon', k: ['月亮'] },
      { c: '⭐', n: 'star', k: ['星星'] },
      { c: '🌟', n: 'glowing star', k: ['闪星'] },
      { c: '✨', n: 'sparkles', k: ['闪光'] },
      { c: '⚡', n: 'lightning', k: ['闪电'] },
      { c: '🔥', n: 'fire', k: ['火', '热门'] },
      { c: '🌈', n: 'rainbow', k: ['彩虹'] },
      { c: '☁️', n: 'cloud', k: ['云'] },
      { c: '❄️', n: 'snowflake', k: ['雪花'] },
      { c: '💧', n: 'droplet', k: ['水滴'] },
      { c: '🌊', n: 'wave', k: ['海浪'] },
      { c: '🎉', n: 'party', k: ['庆祝', '派对'] },
      { c: '🎊', n: 'confetti', k: ['彩纸'] },
      { c: '🎁', n: 'gift', k: ['礼物'] },
      { c: '🎈', n: 'balloon', k: ['气球'] },
      { c: '🎂', n: 'cake', k: ['蛋糕'] },
      { c: '🍰', n: 'shortcake', k: ['短蛋糕'] },
      { c: '🚀', n: 'rocket', k: ['火箭'] },
      { c: '✈️', n: 'plane', k: ['飞机'] },
      { c: '🌍', n: 'earth', k: ['地球'] },
      { c: '🌎', n: 'earth americas', k: ['美洲'] },
      { c: '🌏', n: 'earth asia', k: ['亚洲'] },
    ],
  },
  {
    id: 'tech',
    title: '科技 & 办公',
    items: [
      { c: '💻', n: 'laptop', k: ['电脑'] },
      { c: '🖥️', n: 'desktop', k: ['台式'] },
      { c: '🖨️', n: 'printer', k: ['打印机'] },
      { c: '⌨️', n: 'keyboard', k: ['键盘'] },
      { c: '🖱️', n: 'mouse', k: ['鼠标'] },
      { c: '🖲️', n: 'trackball', k: ['轨迹球'] },
      { c: '💽', n: 'minidisc', k: ['光盘'] },
      { c: '💾', n: 'floppy disk', k: ['软盘', '保存'] },
      { c: '💿', n: 'cd', k: ['CD'] },
      { c: '📀', n: 'dvd', k: ['DVD'] },
      { c: '📱', n: 'phone', k: ['手机'] },
      { c: '☎️', n: 'telephone', k: ['电话'] },
      { c: '📞', n: 'phone receiver', k: ['听筒'] },
      { c: '📟', n: 'pager', k: ['寻呼机'] },
      { c: '📠', n: 'fax', k: ['传真'] },
      { c: '🔋', n: 'battery', k: ['电池'] },
      { c: '🔌', n: 'plug', k: ['插头'] },
      { c: '📺', n: 'tv', k: ['电视'] },
      { c: '📷', n: 'camera', k: ['相机'] },
      { c: '🎥', n: 'movie camera', k: ['摄像机'] },
      { c: '📹', n: 'video camera', k: ['摄像'] },
      { c: '🎮', n: 'game', k: ['游戏'] },
      { c: '🕹️', n: 'joystick', k: ['摇杆'] },
      { c: '🎙️', n: 'studio mic', k: ['麦克风'] },
      { c: '🎚️', n: 'level slider', k: ['滑块'] },
      { c: '🎛️', n: 'control knobs', k: ['控制'] },
      { c: '📡', n: 'satellite', k: ['卫星天线'] },
      { c: '🔍', n: 'magnifying left', k: ['搜索'] },
      { c: '🔎', n: 'magnifying right', k: ['查找'] },
      { c: '💡', n: 'bulb', k: ['灯泡', '想法'] },
      { c: '🔦', n: 'flashlight', k: ['手电'] },
      { c: '🕯️', n: 'candle', k: ['蜡烛'] },
      { c: '📔', n: 'notebook deco', k: ['笔记'] },
      { c: '📕', n: 'closed book', k: ['书'] },
      { c: '📖', n: 'open book', k: ['书'] },
      { c: '📗', n: 'green book', k: ['绿书'] },
      { c: '📘', n: 'blue book', k: ['蓝书'] },
      { c: '📙', n: 'orange book', k: ['橙书'] },
      { c: '📚', n: 'books', k: ['书堆'] },
      { c: '📓', n: 'notebook', k: ['笔记本'] },
      { c: '📒', n: 'ledger', k: ['账本'] },
      { c: '📃', n: 'page curl', k: ['卷页'] },
      { c: '📜', n: 'scroll', k: ['卷轴'] },
      { c: '📄', n: 'page', k: ['页'] },
      { c: '📰', n: 'newspaper', k: ['报纸'] },
      { c: '📑', n: 'bookmark tabs', k: ['书签'] },
      { c: '🔖', n: 'bookmark', k: ['书签'] },
      { c: '🏷️', n: 'label', k: ['标签'] },
      { c: '💰', n: 'money bag', k: ['钱袋'] },
      { c: '💴', n: 'yen', k: ['日元'] },
      { c: '💵', n: 'dollar', k: ['美元'] },
      { c: '💶', n: 'euro', k: ['欧元'] },
      { c: '💷', n: 'pound', k: ['英镑'] },
      { c: '💸', n: 'money wings', k: ['烧钱'] },
      { c: '💳', n: 'credit card', k: ['信用卡'] },
      { c: '🧾', n: 'receipt', k: ['收据'] },
      { c: '✉️', n: 'envelope', k: ['信封'] },
      { c: '📧', n: 'email', k: ['邮件'] },
      { c: '📨', n: 'incoming envelope', k: ['收件'] },
      { c: '📩', n: 'envelope arrow', k: ['发件'] },
      { c: '📤', n: 'outbox', k: ['发件箱'] },
      { c: '📥', n: 'inbox', k: ['收件箱'] },
      { c: '📦', n: 'package', k: ['包裹'] },
      { c: '📫', n: 'mailbox closed', k: ['邮箱'] },
      { c: '🗳️', n: 'ballot box', k: ['投票'] },
      { c: '📌', n: 'pushpin', k: ['图钉'] },
      { c: '📎', n: 'paperclip', k: ['回形针'] },
      { c: '📏', n: 'ruler', k: ['尺'] },
      { c: '📐', n: 'triangular ruler', k: ['三角尺'] },
      { c: '✂️', n: 'scissors', k: ['剪刀'] },
      { c: '🖊️', n: 'pen', k: ['笔'] },
      { c: '🖋️', n: 'fountain pen', k: ['钢笔'] },
      { c: '✏️', n: 'pencil', k: ['铅笔'] },
      { c: '🖍️', n: 'crayon', k: ['蜡笔'] },
      { c: '🖌️', n: 'paintbrush', k: ['画笔'] },
    ],
  },
  {
    id: 'symbols',
    title: '符号 & 标记',
    items: [
      { c: '✅', n: 'check', k: ['对勾'] },
      { c: '❌', n: 'cross', k: ['叉', '错误'] },
      { c: '❎', n: 'cross button', k: ['错'] },
      { c: '✔️', n: 'check mark', k: ['对勾'] },
      { c: '❗', n: 'exclamation', k: ['感叹号'] },
      { c: '❓', n: 'question', k: ['问号'] },
      { c: '❔', n: 'white question', k: ['问号'] },
      { c: '❕', n: 'white exclamation', k: ['感叹号'] },
      { c: '‼️', n: 'double exclamation', k: ['双感叹'] },
      { c: '⁉️', n: 'exclamation question', k: ['问感叹'] },
      { c: '⭕', n: 'circle', k: ['圈'] },
      { c: '🔴', n: 'red circle', k: ['红'] },
      { c: '🟠', n: 'orange circle', k: ['橙'] },
      { c: '🟡', n: 'yellow circle', k: ['黄'] },
      { c: '🟢', n: 'green circle', k: ['绿'] },
      { c: '🔵', n: 'blue circle', k: ['蓝'] },
      { c: '🟣', n: 'purple circle', k: ['紫'] },
      { c: '🟤', n: 'brown circle', k: ['棕'] },
      { c: '⚫', n: 'black circle', k: ['黑'] },
      { c: '⚪', n: 'white circle', k: ['白'] },
      { c: '🟥', n: 'red square', k: ['红方'] },
      { c: '🟧', n: 'orange square', k: ['橙方'] },
      { c: '🟨', n: 'yellow square', k: ['黄方'] },
      { c: '🟩', n: 'green square', k: ['绿方'] },
      { c: '🟦', n: 'blue square', k: ['蓝方'] },
      { c: '🟪', n: 'purple square', k: ['紫方'] },
      { c: '🟫', n: 'brown square', k: ['棕方'] },
      { c: '⬛', n: 'black square', k: ['黑方'] },
      { c: '⬜', n: 'white square', k: ['白方'] },
      { c: '◾', n: 'small black square', k: ['小方'] },
      { c: '◽', n: 'small white square', k: ['小方'] },
      { c: '▶️', n: 'play', k: ['播放'] },
      { c: '◀️', n: 'reverse', k: ['倒退'] },
      { c: '⏯️', n: 'play pause', k: ['暂停'] },
      { c: '⏸️', n: 'pause', k: ['暂停'] },
      { c: '⏹️', n: 'stop', k: ['停止'] },
      { c: '⏺️', n: 'record', k: ['录制'] },
      { c: '⏭️', n: 'next', k: ['下一首'] },
      { c: '⏮️', n: 'previous', k: ['上一首'] },
      { c: '⏩', n: 'fast forward', k: ['快进'] },
      { c: '⏪', n: 'rewind', k: ['后退'] },
      { c: '🔼', n: 'up button', k: ['向上'] },
      { c: '🔽', n: 'down button', k: ['向下'] },
      { c: '⬆️', n: 'up arrow', k: ['上'] },
      { c: '⬇️', n: 'down arrow', k: ['下'] },
      { c: '⬅️', n: 'left arrow', k: ['左'] },
      { c: '➡️', n: 'right arrow', k: ['右'] },
      { c: '↗️', n: 'upper right', k: ['右上'] },
      { c: '↘️', n: 'lower right', k: ['右下'] },
      { c: '↙️', n: 'lower left', k: ['左下'] },
      { c: '↖️', n: 'upper left', k: ['左上'] },
      { c: '↕️', n: 'up down', k: ['上下'] },
      { c: '↔️', n: 'left right', k: ['左右'] },
      { c: '🔄', n: 'refresh', k: ['刷新'] },
      { c: '🔁', n: 'repeat', k: ['循环'] },
      { c: '🔂', n: 'repeat one', k: ['单曲循环'] },
      { c: '🔀', n: 'shuffle', k: ['随机'] },
      { c: '➕', n: 'plus', k: ['加'] },
      { c: '➖', n: 'minus', k: ['减'] },
      { c: '✖️', n: 'multiply', k: ['乘'] },
      { c: '➗', n: 'divide', k: ['除'] },
      { c: '🟰', n: 'equals', k: ['等于'] },
      { c: '♾️', n: 'infinity', k: ['无穷'] },
      { c: '💲', n: 'dollar sign', k: ['美元符号'] },
      { c: '💱', n: 'currency exchange', k: ['汇率'] },
      { c: '™️', n: 'trademark', k: ['TM'] },
      { c: '©️', n: 'copyright', k: ['版权'] },
      { c: '®️', n: 'registered', k: ['注册'] },
      { c: '〰️', n: 'wavy dash', k: ['波浪线'] },
      { c: '💠', n: 'diamond shape', k: ['菱形'] },
      { c: '🔱', n: 'trident', k: ['三叉戟'] },
      { c: '🔰', n: 'beginner', k: ['新手'] },
      { c: '⚜️', n: 'fleur-de-lis', k: ['百合花饰'] },
      { c: '🔘', n: 'radio button', k: ['单选'] },
      { c: '🔲', n: 'black square button', k: ['黑方按钮'] },
      { c: '🔳', n: 'white square button', k: ['白方按钮'] },
    ],
  },
];
